# Numpy 미니 퀘스트

In [31]:
import numpy as np

## 차원 - 미니 퀘스트

### 1번 퀘스트
다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.

In [32]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr.ndim)

3


### 2번 퀘스트
1차원 배열 `[10, 20, 30, 40, 50, 60]`을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.

In [33]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr.reshape(2, 3))

[[10 20 30]
 [40 50 60]]


### 3번 퀘스트
다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.
- `newaxis`를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.

In [34]:
arr = np.array([7, 14, 21])
arr = arr[:, np.newaxis]

print(f"Shape: {arr.shape},\tDim: {arr.ndim}")

Shape: (3, 1),	Dim: 2


## Shape - 미니 퀘스트

### 1번 퀘스트
주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


### 2번 퀘스트
1차원 배열 `[10, 20, 30, 40, 50, 60]`을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.

In [36]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr.reshape(2, 3).shape)

(2, 3)


### 3번 퀘스트
다음 1차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요.

In [37]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print(arr.reshape(3, 2, 2).shape)

(3, 2, 2)


## 데이터 타입 - 미니 퀘스트

### 1번 퀘스트
아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.

In [38]:
arr = np.array([10, 20, 30])

print(arr.dtype)

int64


### 2번 퀘스트
정수형 배열 `[1, 2, 3]`을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.

In [39]:
arr = np.array([1, 2, 3])
arr = arr.astype(np.float64)

print(arr.dtype)

float64


### 3번 퀘스트
NumPy 배열 `[100, 200, 300]`을 `uint8`로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.

In [40]:
arr = np.array([100, 200, 300])
arr = arr.astype(np.uint8)

print(arr.itemsize)

1


## 인덱싱 - 미니 퀘스트

### 1번 퀘스트
주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.

In [41]:
arr = np.array([10, 20, 30, 40, 50])

print(f"첫 번째 요소: {arr[0]}")
print(f"마지막 요소: {arr[-1]}")

첫 번째 요소: 10
마지막 요소: 50


### 2번 퀘스트
주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.

In [42]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"첫 번째 열: {matrix[:, 0]}")
print(f"두 번째 열: {matrix[1, :]}")


첫 번째 열: [1 4 7]
두 번째 열: [4 5 6]


### 3번 퀘스트
주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.

In [43]:
arr = np.array([5, 15, 8, 20, 3, 12])

upper_10 = arr > 10
indices = []
for idx, is_upper_10 in enumerate(upper_10):
    if is_upper_10:
        indices.append(idx)

print(f"10보다 큰 요소들: {arr[upper_10]}")
print(f"10보단 큰 요소들의 index: {indices}")

10보다 큰 요소들: [15 20 12]
10보단 큰 요소들의 index: [1, 3, 5]


## 연산 - 미니 퀘스트

### 1번 퀘스트
주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.

In [44]:
arr = np.array([1, 2, 3])
brr = np.array([4, 5, 6])

print(arr + brr)

[5 7 9]


### 2번 퀘스트
다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 `[1, 2, 3]`을 더하는 코드를 작성하세요.

In [45]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
vector = np.array([1, 2, 3])

print(matrix + vector)

[[11 22 33]
 [41 52 63]]


### 3번 퀘스트
주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.

In [46]:
arr = np.array([
    [3, 7, 2],
    [8, 4, 6]
])

print(f"Axis 0: {arr.max(axis=0)}")
print(f"Axis 1: {arr.max(axis=1)}")

Axis 0: [8 7 6]
Axis 1: [7 8]


## 유니버셜 함수 - 미니 퀘스트

### 1번 퀘스트
배열 `[1, 2, 3, 4]`에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요. 

In [47]:
arr = np.array([1, 2, 3, 4])

print(np.square(arr))

[ 1  4  9 16]


### 2번 퀘스트
다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.

In [48]:
arr = np.array([10, 20, 30])
brr = np.array([1, 2, 3])

arr = arr + brr
print(arr, brr)

[11 22 33] [1 2 3]


### 3번 퀘스트
다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고, 특정 조건(`log 값 > 1`)을 만족하는 요소만 출력하는 코드를 작성하세요.

In [49]:
arr = np.array([1, np.e, 10, 100])

print(arr[np.log(arr) > 1])

[ 10. 100.]
