# Numpy 미니 퀘스트

In [2]:
import numpy as np

## 차원 - 미니 퀘스트

### 1번 퀘스트

In [3]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr.ndim)

3


### 2번 퀘스트

In [4]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr.reshape(2, 3))

[[10 20 30]
 [40 50 60]]


### 3번 퀘스트

In [5]:
arr = np.array([7, 14, 21])
arr = arr[:, np.newaxis]

print(f"Shape: {arr.shape},\tDim: {arr.ndim}")

Shape: (3, 1),	Dim: 2


## Shape - 미니 퀘스트

### 1번 퀘스트

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


### 2번 퀘스트

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr.reshape(2, 3).shape)

(2, 3)


### 3번 퀘스트

In [8]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print(arr.reshape(3, 2, 2).shape)

(3, 2, 2)


## 데이터 타입 - 미니 퀘스트

### 1번 퀘스트

In [10]:
arr = np.array([10, 20, 30])

print(arr.dtype)

int64


### 2번 퀘스트

In [11]:
arr = np.array([1, 2, 3])
arr = arr.astype(np.float64)

print(arr.dtype)

float64


### 3번 퀘스트

In [12]:
arr = np.array([100, 200, 300])
arr = arr.astype(np.uint8)

print(arr.itemsize)

1


## 인덱싱 - 미니 퀘스트

### 1번 퀘스트

In [21]:
arr = np.array([10, 20, 30, 40, 50])

print(f"첫 번째 요소: {arr[0]}")
print(f"마지막 요소: {arr[-1]}")

첫 번째 요소: 10
마지막 요소: 50


### 2번 퀘스트

In [19]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"첫 번째 열: {matrix[:, 0]}")
print(f"두 번째 열: {matrix[1, :]}")


첫 번째 열: [1 4 7]
두 번째 열: [4 5 6]


### 3번 퀘스트

In [22]:
arr = np.array([5, 15, 8, 20, 3, 12])

upper_10 = arr > 10
indices = []
for idx, is_upper_10 in enumerate(upper_10):
    if is_upper_10:
        indices.append(idx)

print(f"10보다 큰 요소들: {arr[upper_10]}")
print(f"10보단 큰 요소들의 index: {indices}")

10보다 큰 요소들: [15 20 12]
10보단 큰 요소들의 index: [1, 3, 5]


## 연산 - 미니 퀘스트

### 1번 퀘스트

In [23]:
arr = np.array([1, 2, 3])
brr = np.array([4, 5, 6])

print(arr + brr)

[5 7 9]


### 2번 퀘스트

In [24]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
vector = np.array([1, 2, 3])

print(matrix + vector)

[[11 22 33]
 [41 52 63]]


### 3번 퀘스트

In [25]:
arr = np.array([
    [3, 7, 2],
    [8, 4, 6]
])

print(f"Axis 0: {arr.max(axis=0)}")
print(f"Axis 1: {arr.max(axis=1)}")

Axis 0: [8 7 6]
Axis 1: [7 8]


## 유니버셜 함수 - 미니 퀘스트

### 1번 퀘스트

In [26]:
arr = np.array([1, 2, 3, 4])

print(np.square(arr))

[ 1  4  9 16]


### 2번 퀘스트

In [29]:
arr = np.array([10, 20, 30])
brr = np.array([1, 2, 3])

arr = arr + brr
print(arr, brr)

[11 22 33] [1 2 3]


### 3번 퀘스트

In [30]:
arr = np.array([1, np.e, 10, 100])

print(arr[np.log(arr) > 1])

[ 10. 100.]
